# Generated by Django 4.0.2 on 2022-05-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_content_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.content'),
        ),
    ]
