# Generated by Django 4.0.2 on 2022-05-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_remove_experience_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.content'),
        ),
    ]
